// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict'

console.log('Hello, BuckleScript and Reason!')

var figures = /* :: */[
  /* record */[
    /* kind : King */0,
    /* color : White */0,
    /* position : tuple */[
      /* "A" */65,
      1
    ]
  ],
  /* :: */[
    /* record */[
      /* kind : Rook */4,
      /* color : Black */1,
      /* position : tuple */[
        /* "C" */67,
        7
      ]
    ],
    /* [] */0
  ]
]

exports.figures = figures
/*  Not a pure module */
