// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");

var figures = /* :: */[
  /* record */[
    /* kind : King */0,
    /* color : White */0,
    /* position : tuple */[
      /* "A" */65,
      1
    ]
  ],
  /* :: */[
    /* record */[
      /* kind : Rook */4,
      /* color : Black */1,
      /* position : tuple */[
        /* "C" */67,
        7
      ]
    ],
    /* [] */0
  ]
];

function stringOfColor(col) {
  if (col) {
    return "Black";
  } else {
    return "White";
  }
}

function stringOfKind(knd) {
  switch (knd) {
    case /* King */0 :
        return "King";
    case /* Queen */1 :
        return "Queen";
    case /* Bishop */2 :
        return "Bishop";
    case /* Knight */3 :
        return "Knight";
    case /* Rook */4 :
        return "Rook";
    case /* Pawn */5 :
        return "Pawn";
    
  }
}

function stringOfPosition(a, b) {
  return $$String.make(1, a) + String(b);
}

function stringOfFigure(param) {
  var p = param[/* position */2];
  return stringOfKind(param[/* kind */0]) + (", " + ((
              param[/* color */1] ? "Black" : "White"
            ) + (", " + stringOfPosition(p[0], p[1]))));
}

console.log(stringOfFigure(List.nth(figures, 0)));

console.log("Hello, BuckleScript and Reason!");

exports.figures = figures;
exports.stringOfColor = stringOfColor;
exports.stringOfKind = stringOfKind;
exports.stringOfPosition = stringOfPosition;
exports.stringOfFigure = stringOfFigure;
/*  Not a pure module */
