// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Exo2$MyLittlePony = require("./Exo2.bs.js");

function names_of_places__(_res, _places) {
  while(true) {
    var places = _places;
    var res = _res;
    if (places) {
      _places = places[1];
      _res = Belt_List.add(res, places[0][/* name */3]);
      continue ;
    } else {
      return res;
    }
  };
}

function names_of_places(places) {
  var _res_ = /* [] */0;
  var _places_ = places;
  while(true) {
    var places_ = _places_;
    var res_ = _res_;
    if (places_) {
      _places_ = places_[1];
      _res_ = /* :: */[
        places_[0][/* name */3],
        res_
      ];
      continue ;
    } else {
      return res_;
    }
  };
}

console.log(Belt_List.toArray(names_of_places(Exo2$MyLittlePony.places)));

console.log(Belt_List.map(Exo2$MyLittlePony.places, (function (place) {
            return place[/* name */3];
          })));

var places = Exo2$MyLittlePony.places;

exports.places = places;
exports.names_of_places__ = names_of_places__;
exports.names_of_places = names_of_places;
/*  Not a pure module */
